name: CI
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.3'
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      JULIA_PKG_SERVER: ""
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Check build conditions
        run: |
         julia -e '
           function set_environment_variable(name::AbstractString, value::AbstractString)
               github_env = ENV["GITHUB_ENV"]
               touch(github_env)
               open(github_env, "a") do io
                   println(io, "$(name)=$(value)")
               end
           end
           event_name = "${{ github.event_name }}"
           if event_name == "pull_request"
               base_ref = "${{ github.base_ref }}"
               head_ref = "${{ github.head_ref }}"
               base_repository = "${{ github.repository }}"
               head_repository = "${{ github.event.pull_request.head.repo.full_name }}"
               build_docs = (base_ref == "master") && (head_ref == "dev") && (base_repository == head_repository)
           elseif event_name == "push"
               ref = "${{ github.ref }}"
               build_docs = (ref == "refs/heads/master") || (startswith(ref, "refs/tags/"))
           elseif event_name == "schedule"
               build_docs = ref == "refs/heads/master"
           elseif event_name == "workflow_dispatch"
               build_docs = ref == "refs/heads/master"
           else
               build_docs = false
           end
           if build_docs
               @info("We will build the docs")
               set_environment_variable("BUILD_DOCS", "true")
               if event_name == "pull_request"
                   set_environment_variable("GITHUB_EVENT_NAME", "pull_request")
               else
                   set_environment_variable("GITHUB_EVENT_NAME", "push")
               end
           else 
               @info("We will NOT build the docs")
               set_environment_variable("BUILD_DOCS", "false")
           end'
      - name: Install dependencies 
        run: |
          julia --project=docs -e '
            if ENV["BUILD_DOCS"] == "true"
                using Pkg
                Pkg.develop(PackageSpec(path=pwd()))
                Pkg.instantiate()
            end'
      - name: Doctest
        run: |
          julia --project=docs -e '
            if ENV["BUILD_DOCS"] == "true"
                using Documenter: doctest
                using NearestNeighborModels, MLJBase
                @info "attempting to run the doctests"
                doctest(NearestNeighborModels)
            else
                @info "skipping the doctests"
            end'
      - name: Build and deploy
        run: julia --project=docs -e '
            if ENV["BUILD_DOCS"] == "true"
                @info "attempting to build and deploy docs"
                run(`julia --project=docs --color=yes docs/make.jl`)
                @info "successfully built and deployed docs"
            else
                @info "skipping doc build and deploy"
            end'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
