name: Generate and Deploy Documentation
on:
  push:
    branches:
      - dev
    tags: [v*]
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      actions: write
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/cache@v3
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
          show-versioninfo: true
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=joinpath(pwd(), "NearestNeighborModels")))'
      - uses: julia-actions/julia-docdeploy@v1
        with:
          install-package: false # because we manually installed above
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          DOCUMENTER_DEBUG: "true"
